jobs:
  -
    job: '${{ parameters.tag }}'
    timeoutInMinutes: 0
    pool:
      vmImage: ubuntu-latest
    dependsOn: '${{ parameters.dep }}'
    steps:
      -
        script: 'sudo df -h; sudo rm -rf /usr/share/dotnet; sudo df -h;'
      -
        script: 'docker build --force-rm -f internal/docker/${{ parameters.file }} -t dsandor/qt:${{ parameters.tag }} .'
      -
        script: 'docker login -u therecipe -p $(DOCKER_PASSWORD) && docker push dsandor/qt:${{ parameters.tag }} && docker logout'
